abyssinian:	abyssinian
aegean:	aegean
american_curl:	american_curl
american_bobtail:	american_bobtail
american_shorthair:	american_shorthair
american_wirehair:	american_wirehair
aphrodite_giant:	aphrodite_giant
arabian_mau:	arabian_mau
australian_mist:	australian_mist
asian:	asian
asian_semi_longhair:	asian_semi_longhair
balinese:	balinese
bambino:	bambino
bengal:	bengal
birman:	birman
bombay:	bombay
brazilian_shorthair:	brazilian_shorthair
british_semi_longhair:	british_semi_longhair
british_shorthair:	british_shorthair
british_longhair:	british_longhair
burmese:	burmese
burmilla:	burmilla
california_spangled:	california_spangled
chantilly_tiffany:	chantilly_tiffany
chartreux:	chartreux
chausie:	chausie
cheetoh:	cheetoh
colorpoint_shorthair:	colorpoint_shorthair
cornish_rex:	cornish_rex
cymric_or:	cymric_or
manx_longhair:	manx_longhair
longhaired_manx:	longhaired_manx
cyprus:	cyprus
devon_rex:	devon_rex
donskoy_or:	donskoy_or
don_sphynx:	don_sphynx
dragon_li_or:	dragon_li_or
chinese_li_hua:	chinese_li_hua
dwelf:	dwelf
egyptian_mau:	egyptian_mau
european_shorthair:	european_shorthair
exotic_shorthair:	exotic_shorthair
foldex:	foldex
german_rex:	german_rex
havana_brown:	havana_brown
highlander:	highlander
himalayan_or:	himalayan_or
colorpoint_persian:	colorpoint_persian
japanese_bobtail:	japanese_bobtail
javanese_or:	javanese_or
colorpoint_longhair:	colorpoint_longhair
karelian_bobtail:	karelian_bobtail
khao_manee:	khao_manee
korat:	korat
korean_bobtail:	korean_bobtail
korn_ja:	korn_ja
kurilian_bobtail_or:	kurilian_bobtail_or
kuril_islands_bobtail:	kuril_islands_bobtail
laperm:	laperm
lykoi:	lykoi
maine_coon:	maine_coon
manx:	manx
mekong_bobtail:	mekong_bobtail
minskin:	minskin
munchkin:	munchkin
nebelung:	nebelung
napoleon:	napoleon
norwegian_forest_cat:	norwegian_forest_cat
ocicat:	ocicat
ojos_azules:	ojos_azules
oregon_rex:	oregon_rex
oriental_bicolor:	oriental_bicolor
oriental_shorthair:	oriental_shorthair
oriental_longhair:	oriental_longhair
foreign_longhair:	foreign_longhair
mandarin:	mandarin
british_angora:	british_angora
persian:	persian
peterbald:	peterbald
pixie_bob:	pixie_bob
raas:	raas
ragamuffin:	ragamuffin
liebling:	liebling
ragdoll:	ragdoll
russian_blue:	russian_blue
russian_white:	russian_white
sam_sawet:	sam_sawet
savannah:	savannah
scottish_fold:	scottish_fold
selkirk_rex:	selkirk_rex
serengeti:	serengeti
serrade_petit:	serrade_petit
siamese:	siamese
siberian:	siberian
neva_masquerade:	neva_masquerade
singapura:	singapura
snowshoe:	snowshoe
sokoke:	sokoke
somali:	somali
sphynx:	sphynx
suphalak:	suphalak
thai_or:	thai_or
wichien_maat:	wichien_maat
thai_lilac:	thai_lilac
tonkinese:	tonkinese
toyger:	toyger
turkish_angora:	turkish_angora
turkish_van:	turkish_van
ukrainian_levkoy:	ukrainian_levkoy
wila_krungthep:	wila_krungthep
york_chocolate:	york_chocolate
